### ISSUE TITLE
Spring tool suite hibaüzenet lokális szerver futtatása közben

### ISSUE THREAD

**Issue by domokosdaniel56** [domokosdaniel56/cosy#1]
[20200325_091906.zip](https://github.com/domokosdaniel56/cosy/files/4379759/20200325_091906.zip)

**Comment by domokosdaniel56** [comment]
Teszt komment webhook-hoz.

**Comment by wirthandras** [comment]
@domokosdaniel56 annyi a különbség, hogy én 4.0.0-ás STS-t használok te pedig 4.3.2-eset. Ezt a tény megállapítást teszem. További vizsgálódás szükséges.

**Comment by wirthandras** [comment]
https://stackoverflow.com/questions/60010007/basic-spring-boot-app-not-working-showing-failed-to-refresh-live-data-from-pro

Itt az utolsó javaslatban szereplő spring.devtools.livereload.enabled=true -t kipróbálnád?

**Comment by domokosdaniel56** [comment]
A sor beszúrása után is jelentkezik a probléma, lehet akkor jobb ötlet lenne újratelepítenem a te verzióddal.
